Fixed icons
Nodrex/Testomania pull request #368
Opened 2023-04-14 18:22 UTC by Nodrex

2023-05-06 14:16 UTC, shalva97 requested changes
its strange, why do you have pics in this PR

2023-05-06 14:16 UTC, shalva97 commented on testomania/src/main/ic_launcher-playstore.png
this adds 80KB. Convert to bitmap

2023-05-06 19:49 UTC, Nodrex commented on testomania/src/main/ic_launcher-playstore.png
If you remember we have problem with icon on m device so I fixed it and that's why we have this PR

2023-05-07 09:13 UTC, shalva97 commented on testomania/src/main/ic_launcher-playstore.png
does it really help? this pic was meant to be uploaded to Play Store, its name also says that

2023-05-08 19:21 UTC, Nodrex commented on testomania/src/main/ic_launcher-playstore.png
Yep on my device it helps, how about on yours? @shalva97

2023-05-10 09:31 UTC, shalva97 commented on testomania/src/main/ic_launcher-playstore.png
Can you convert them to webp?

2023-05-10 19:14 UTC, Nodrex commented on testomania/src/main/ic_launcher-playstore.png
I am not sure that for the App icon, it is a good ide.
Are you sure that this will work?

2023-05-11 13:29 UTC, shalva97 commented on testomania/src/main/ic_launcher-playstore.png
yes, why would not it? is not it worse to have +80KB added to the app?

2023-05-12 09:26 UTC, Nodrex commented
@shalva97 I am only able to convert the foreground launcher in to webp. others were skipped automatically when I tried conversation with android studio

2023-05-12 09:29 UTC, shalva97 commented
How did you convert it? Usually right click -> conver to webp works.

Any idea why Android Studio skips them?

2023-05-12 09:35 UTC, Nodrex commented
> How did you convert it? Usually right click -> conver to webp works.
> 
> Any idea why Android Studio skips them?

Yep used right click -> convert to webp and I got message that it was skipped because gain of in size was 0 kb

![Unsdfsdfsdftitled](https://github.com/Nodrex/Testomania/assets/6556678/d49bbca3-3e10-4854-814c-e4c9efd3e1d0)

2023-05-12 09:45 UTC, shalva97 approved these changes

2023-05-12 10:06 UTC, Nodrex commented
> wait that image is not in resources folder, it wont be included in the app. Why you did not say it at the start :D

This is what I told fro the beginning :D This is an icon :D

2023-05-12 10:06 UTC, merged